// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module infinite_sea_common::battle_status {
    use std::vector;

    public fun in_progress(): u8 {
        0
    }

    public fun ended(): u8 {
        1
    }

    public fun looted(): u8 {
        2
    }

    public fun is_valid(v: u8): bool {
        v == in_progress() || v == ended() || v == looted()
    }

    public fun are_all_valid(vs: &vector<u8>): bool {
        let i = 0;
        let l = vector::length(vs);
        while (i < l) {
            if (!is_valid(*vector::borrow(vs, i))) {
                return false
            };
            i = i + 1;
        };
        true
    }
}
