// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module infinite_sea_common::daily_quests {
    #[allow(unused_const)]
    const EDataTooLong: u64 = 102;

    struct DailyQuests has store, drop, copy {
        start_time: u64,
        craft_ships: u8,
        sail_distance: u64,
        beat_e_roster: u8,
        beat_p_roster: u8,
    }

    public fun new(
        start_time: u64,
        craft_ships: u8,
        sail_distance: u64,
        beat_e_roster: u8,
        beat_p_roster: u8,
    ): DailyQuests {
        let daily_quests = DailyQuests {
            start_time,
            craft_ships,
            sail_distance,
            beat_e_roster,
            beat_p_roster,
        };
        validate(&daily_quests);
        daily_quests
    }

    fun validate(daily_quests: &DailyQuests) {
        let _ = daily_quests;
    }

    public fun start_time(daily_quests: &DailyQuests): u64 {
        daily_quests.start_time
    }

    public fun craft_ships(daily_quests: &DailyQuests): u8 {
        daily_quests.craft_ships
    }

    public fun sail_distance(daily_quests: &DailyQuests): u64 {
        daily_quests.sail_distance
    }

    public fun beat_e_roster(daily_quests: &DailyQuests): u8 {
        daily_quests.beat_e_roster
    }

    public fun beat_p_roster(daily_quests: &DailyQuests): u8 {
        daily_quests.beat_p_roster
    }

}
