// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module infinite_sea_common::experience_table_item {
    #[allow(unused_const)]
    const EDataTooLong: u64 = 102;

    struct ExperienceTableItem has store, drop, copy {
        level: u16,
        experience: u32,
        difference: u32,
    }

    public fun new(
        level: u16,
        experience: u32,
        difference: u32,
    ): ExperienceTableItem {
        let experience_table_item = ExperienceTableItem {
            level,
            experience,
            difference,
        };
        validate(&experience_table_item);
        experience_table_item
    }

    fun validate(experience_table_item: &ExperienceTableItem) {
        let _ = experience_table_item;
    }

    public fun level(experience_table_item: &ExperienceTableItem): u16 {
        experience_table_item.level
    }

    public fun experience(experience_table_item: &ExperienceTableItem): u32 {
        experience_table_item.experience
    }

    public fun difference(experience_table_item: &ExperienceTableItem): u32 {
        experience_table_item.difference
    }

}
