// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module infinite_sea_common::experience_level {
    #[allow(unused_const)]
    const EDataTooLong: u64 = 102;

    struct ExperienceLevel has store, drop, copy {
        level: u16,
        experience: u32,
        difference: u32,
    }

    public fun new(
        level: u16,
        experience: u32,
        difference: u32,
    ): ExperienceLevel {
        let experience_level = ExperienceLevel {
            level,
            experience,
            difference,
        };
        validate(&experience_level);
        experience_level
    }

    fun validate(experience_level: &ExperienceLevel) {
        let _ = experience_level;
    }

    public fun level(experience_level: &ExperienceLevel): u16 {
        experience_level.level
    }

    public fun experience(experience_level: &ExperienceLevel): u32 {
        experience_level.experience
    }

    public fun difference(experience_level: &ExperienceLevel): u32 {
        experience_level.difference
    }

}
