// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module infinite_sea_common::island_resource_type {
    use std::vector;

    public fun seed(): u8 {
        0
    }

    public fun wood(): u8 {
        1
    }

    public fun fish(): u8 {
        2
    }

    public fun mineral(): u8 {
        3
    }

    public fun is_valid(v: u8): bool {
        v == seed() || v == wood() || v == fish() || v == mineral()
    }

    public fun are_all_valid(vs: &vector<u8>): bool {
        let i = 0;
        let l = vector::length(vs);
        while (i < l) {
            if (!is_valid(*vector::borrow(vs, i))) {
                return false
            };
            i = i + 1;
        };
        true
    }
}
