// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module infinite_sea_common::item_creation {
    #[allow(unused_const)]
    const EDataTooLong: u64 = 102;

    struct ItemCreation has store, drop, copy {
        requirements_level: u16,
        base_quantity: u32,
        base_experience: u32,
        base_creation_time: u64,
        energy_cost: u32,
    }

    public fun new(
        requirements_level: u16,
        base_quantity: u32,
        base_experience: u32,
        base_creation_time: u64,
        energy_cost: u32,
    ): ItemCreation {
        let item_creation = ItemCreation {
            requirements_level,
            base_quantity,
            base_experience,
            base_creation_time,
            energy_cost,
        };
        validate(&item_creation);
        item_creation
    }

    fun validate(item_creation: &ItemCreation) {
        let _ = item_creation;
    }

    public fun requirements_level(item_creation: &ItemCreation): u16 {
        item_creation.requirements_level
    }

    public fun base_quantity(item_creation: &ItemCreation): u32 {
        item_creation.base_quantity
    }

    public fun base_experience(item_creation: &ItemCreation): u32 {
        item_creation.base_experience
    }

    public fun base_creation_time(item_creation: &ItemCreation): u64 {
        item_creation.base_creation_time
    }

    public fun energy_cost(item_creation: &ItemCreation): u32 {
        item_creation.energy_cost
    }

}
