// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module infinite_sea_common::item_id_quantity_pair {
    #[allow(unused_const)]
    const EDataTooLong: u64 = 102;

    struct ItemIdQuantityPair has store, drop, copy {
        item_id: u32,
        quantity: u32,
    }

    public fun new(
        item_id: u32,
        quantity: u32,
    ): ItemIdQuantityPair {
        let item_id_quantity_pair = ItemIdQuantityPair {
            item_id,
            quantity,
        };
        validate(&item_id_quantity_pair);
        item_id_quantity_pair
    }

    fun validate(item_id_quantity_pair: &ItemIdQuantityPair) {
        let _ = item_id_quantity_pair;
    }

    public fun item_id(item_id_quantity_pair: &ItemIdQuantityPair): u32 {
        item_id_quantity_pair.item_id
    }

    public fun quantity(item_id_quantity_pair: &ItemIdQuantityPair): u32 {
        item_id_quantity_pair.quantity
    }

}
