// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module infinite_sea_common::newbie_initial_quests {
    #[allow(unused_const)]
    const EDataTooLong: u64 = 102;

    struct NewbieInitialQuests has store, drop, copy {
        create_wallet: bool,
        claim_island: bool,
        cut_woods: u8,
        mine_ores: u8,
        plant_cottons: u8,
        craft_ships: u8,
        beat_e_roster: u8,
    }

    public fun new(
        create_wallet: bool,
        claim_island: bool,
        cut_woods: u8,
        mine_ores: u8,
        plant_cottons: u8,
        craft_ships: u8,
        beat_e_roster: u8,
    ): NewbieInitialQuests {
        let newbie_initial_quests = NewbieInitialQuests {
            create_wallet,
            claim_island,
            cut_woods,
            mine_ores,
            plant_cottons,
            craft_ships,
            beat_e_roster,
        };
        validate(&newbie_initial_quests);
        newbie_initial_quests
    }

    fun validate(newbie_initial_quests: &NewbieInitialQuests) {
        let _ = newbie_initial_quests;
    }

    public fun create_wallet(newbie_initial_quests: &NewbieInitialQuests): bool {
        newbie_initial_quests.create_wallet
    }

    public fun claim_island(newbie_initial_quests: &NewbieInitialQuests): bool {
        newbie_initial_quests.claim_island
    }

    public fun cut_woods(newbie_initial_quests: &NewbieInitialQuests): u8 {
        newbie_initial_quests.cut_woods
    }

    public fun mine_ores(newbie_initial_quests: &NewbieInitialQuests): u8 {
        newbie_initial_quests.mine_ores
    }

    public fun plant_cottons(newbie_initial_quests: &NewbieInitialQuests): u8 {
        newbie_initial_quests.plant_cottons
    }

    public fun craft_ships(newbie_initial_quests: &NewbieInitialQuests): u8 {
        newbie_initial_quests.craft_ships
    }

    public fun beat_e_roster(newbie_initial_quests: &NewbieInitialQuests): u8 {
        newbie_initial_quests.beat_e_roster
    }

}
