// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module infinite_sea_common::roster_status {
    use std::vector;

    public fun at_anchor(): u8 {
        0
    }

    public fun underway(): u8 {
        1
    }

    public fun in_battle(): u8 {
        2
    }

    public fun destroyed(): u8 {
        3
    }

    public fun is_valid(v: u8): bool {
        v == at_anchor() || v == underway() || v == in_battle() || v == destroyed()
    }

    public fun are_all_valid(vs: &vector<u8>): bool {
        let i = 0;
        let l = vector::length(vs);
        while (i < l) {
            if (!is_valid(*vector::borrow(vs, i))) {
                return false
            };
            i = i + 1;
        };
        true
    }
}
