// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module infinite_sea_common::ship_battle_command {
    use std::vector;

    public fun attack(): u8 {
        0
    }

    public fun swap_positions(): u8 {
        1
    }

    public fun pass(): u8 {
        2
    }

    public fun is_valid(v: u8): bool {
        v == attack() || v == swap_positions() || v == pass()
    }

    public fun are_all_valid(vs: &vector<u8>): bool {
        let i = 0;
        let l = vector::length(vs);
        while (i < l) {
            if (!is_valid(*vector::borrow(vs, i))) {
                return false
            };
            i = i + 1;
        };
        true
    }
}
