// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module infinite_sea_common::skill_type_player_id_pair {
    use sui::object::ID;

    #[allow(unused_const)]
    const EDataTooLong: u64 = 102;
    const EInvalidEnumValue: u64 = 106;

    struct SkillTypePlayerIdPair has store, drop, copy {
        skill_type: u8,
        player_id: ID,
    }

    public fun new(
        skill_type: u8,
        player_id: ID,
    ): SkillTypePlayerIdPair {
        let skill_type_player_id_pair = SkillTypePlayerIdPair {
            skill_type,
            player_id,
        };
        validate(&skill_type_player_id_pair);
        skill_type_player_id_pair
    }

    fun validate(skill_type_player_id_pair: &SkillTypePlayerIdPair) {
        assert!(infinite_sea_common::skill_type::is_valid(skill_type_player_id_pair.skill_type), EInvalidEnumValue);
    }

    public fun skill_type(skill_type_player_id_pair: &SkillTypePlayerIdPair): u8 {
        skill_type_player_id_pair.skill_type
    }

    public fun player_id(skill_type_player_id_pair: &SkillTypePlayerIdPair): ID {
        skill_type_player_id_pair.player_id
    }

}
