// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module infinite_sea_common::skill_type {
    use std::vector;

    public fun farming(): u8 {
        0
    }

    public fun woodcutting(): u8 {
        1
    }

    public fun fishing(): u8 {
        2
    }

    public fun mining(): u8 {
        3
    }

    public fun smithing(): u8 {
        4
    }

    public fun cooking(): u8 {
        5
    }

    public fun crafting(): u8 {
        6
    }

    public fun township(): u8 {
        7
    }

    public fun is_valid(v: u8): bool {
        v == farming() || v == woodcutting() || v == fishing() || v == mining() || v == smithing() || v == cooking() || v == crafting() || v == township()
    }

    public fun are_all_valid(vs: &vector<u8>): bool {
        let i = 0;
        let l = vector::length(vs);
        while (i < l) {
            if (!is_valid(*vector::borrow(vs, i))) {
                return false
            };
            i = i + 1;
        };
        true
    }
}
