// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module infinite_sea_common::skill_type_item_id_pair {
    #[allow(unused_const)]
    const EDataTooLong: u64 = 102;
    const EInvalidEnumValue: u64 = 106;

    struct SkillTypeItemIdPair has store, drop, copy {
        skill_type: u8,
        item_id: u32,
    }

    public fun new(
        skill_type: u8,
        item_id: u32,
    ): SkillTypeItemIdPair {
        let skill_type_item_id_pair = SkillTypeItemIdPair {
            skill_type,
            item_id,
        };
        validate(&skill_type_item_id_pair);
        skill_type_item_id_pair
    }

    fun validate(skill_type_item_id_pair: &SkillTypeItemIdPair) {
        assert!(infinite_sea_common::skill_type::is_valid(skill_type_item_id_pair.skill_type), EInvalidEnumValue);
    }

    public fun skill_type(skill_type_item_id_pair: &SkillTypeItemIdPair): u8 {
        skill_type_item_id_pair.skill_type
    }

    public fun item_id(skill_type_item_id_pair: &SkillTypeItemIdPair): u32 {
        skill_type_item_id_pair.item_id
    }

}
