// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module infinite_sea_farming::farming_process {
    use std::option;
    use sui::event;
    use sui::object::{Self, UID};
    use sui::table;
    use sui::transfer;
    use sui::tx_context::TxContext;
    friend infinite_sea_farming::farming_process_aggregate;

    const EIdAlreadyExists: u64 = 101;
    #[allow(unused_const)]
    const EDataTooLong: u64 = 102;
    const EInappropriateVersion: u64 = 103;
    const EEmptyObjectID: u64 = 107;

    struct FarmingProcessTable has key {
        id: UID,
        table: table::Table<address, object::ID>,
    }

    struct FarmingProcessTableCreated has copy, drop {
        id: object::ID,
    }

    fun init(ctx: &mut TxContext) {
        let id_generator_table = FarmingProcessTable {
            id: object::new(ctx),
            table: table::new(ctx),
        };
        let id_generator_table_id = object::uid_to_inner(&id_generator_table.id);
        transfer::share_object(id_generator_table);
        event::emit(FarmingProcessTableCreated {
            id: id_generator_table_id,
        });
    }

    struct FarmingProcess has key {
        id: UID,
        player_id: address,
        version: u64,
        item_id: u32,
        start_time: u64,
        end_time: u64,
    }

    public fun id(farming_process: &FarmingProcess): object::ID {
        object::uid_to_inner(&farming_process.id)
    }

    public fun player_id(farming_process: &FarmingProcess): address {
        farming_process.player_id
    }

    public fun version(farming_process: &FarmingProcess): u64 {
        farming_process.version
    }

    public fun item_id(farming_process: &FarmingProcess): u32 {
        farming_process.item_id
    }

    public(friend) fun set_item_id(farming_process: &mut FarmingProcess, item_id: u32) {
        farming_process.item_id = item_id;
    }

    public fun start_time(farming_process: &FarmingProcess): u64 {
        farming_process.start_time
    }

    public(friend) fun set_start_time(farming_process: &mut FarmingProcess, start_time: u64) {
        farming_process.start_time = start_time;
    }

    public fun end_time(farming_process: &FarmingProcess): u64 {
        farming_process.end_time
    }

    public(friend) fun set_end_time(farming_process: &mut FarmingProcess, end_time: u64) {
        farming_process.end_time = end_time;
    }

    fun new_farming_process(
        player_id: address,
        item_id: u32,
        start_time: u64,
        end_time: u64,
        ctx: &mut TxContext,
    ): FarmingProcess {
        FarmingProcess {
            id: object::new(ctx),
            player_id,
            version: 0,
            item_id,
            start_time,
            end_time,
        }
    }


    public(friend) fun create_farming_process(
        player_id: address,
        item_id: u32,
        start_time: u64,
        end_time: u64,
        farming_process_table: &mut FarmingProcessTable,
        ctx: &mut TxContext,
    ): FarmingProcess {
        let farming_process = new_farming_process(
            player_id,
            item_id,
            start_time,
            end_time,
            ctx,
        );
        asset_player_id_not_exists_then_add(player_id, farming_process_table, object::uid_to_inner(&farming_process.id));
        farming_process
    }

    public(friend) fun asset_player_id_not_exists(
        player_id: address,
        farming_process_table: &FarmingProcessTable,
    ) {
        assert!(!table::contains(&farming_process_table.table, player_id), EIdAlreadyExists);
    }

    fun asset_player_id_not_exists_then_add(
        player_id: address,
        farming_process_table: &mut FarmingProcessTable,
        id: object::ID,
    ) {
        asset_player_id_not_exists(player_id, farming_process_table);
        table::add(&mut farming_process_table.table, player_id, id);
    }

    public(friend) fun transfer_object(farming_process: FarmingProcess, recipient: address) {
        assert!(farming_process.version == 0, EInappropriateVersion);
        transfer::transfer(farming_process, recipient);
    }

    public(friend) fun update_version_and_transfer_object(farming_process: FarmingProcess, recipient: address) {
        update_object_version(&mut farming_process);
        transfer::transfer(farming_process, recipient);
    }

    #[lint_allow(share_owned)]
    public(friend) fun share_object(farming_process: FarmingProcess) {
        assert!(farming_process.version == 0, EInappropriateVersion);
        transfer::share_object(farming_process);
    }

    public(friend) fun freeze_object(farming_process: FarmingProcess) {
        assert!(farming_process.version == 0, EInappropriateVersion);
        transfer::freeze_object(farming_process);
    }

    public(friend) fun update_version_and_freeze_object(farming_process: FarmingProcess) {
        update_object_version(&mut farming_process);
        transfer::freeze_object(farming_process);
    }

    fun update_object_version(farming_process: &mut FarmingProcess) {
        farming_process.version = farming_process.version + 1;
        //assert!(farming_process.version != 0, EInappropriateVersion);
    }

    public(friend) fun drop_farming_process(farming_process: FarmingProcess) {
        let FarmingProcess {
            id,
            player_id: _player_id,
            version: _version,
            item_id: _item_id,
            start_time: _start_time,
            end_time: _end_time,
        } = farming_process;
        object::delete(id);
    }

    #[test_only]
    /// Wrapper of module initializer for testing
    public fun test_init(ctx: &mut TxContext) {
        init(ctx)
    }

}
