// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module infinite_sea::item_creation {
    use infinite_sea_common::skill_type_item_id_pair::SkillTypeItemIdPair;
    use std::option;
    use sui::event;
    use sui::object::{Self, UID};
    use sui::table;
    use sui::transfer;
    use sui::tx_context::TxContext;
    friend infinite_sea::item_creation_create_logic;
    friend infinite_sea::item_creation_update_logic;
    friend infinite_sea::item_creation_aggregate;

    const EIdAlreadyExists: u64 = 101;
    #[allow(unused_const)]
    const EDataTooLong: u64 = 102;
    const EInappropriateVersion: u64 = 103;
    const EEmptyObjectID: u64 = 107;

    struct ItemCreationTable has key {
        id: UID,
        table: table::Table<SkillTypeItemIdPair, object::ID>,
    }

    struct ItemCreationTableCreated has copy, drop {
        id: object::ID,
    }

    fun init(ctx: &mut TxContext) {
        let id_generator_table = ItemCreationTable {
            id: object::new(ctx),
            table: table::new(ctx),
        };
        let id_generator_table_id = object::uid_to_inner(&id_generator_table.id);
        transfer::share_object(id_generator_table);
        event::emit(ItemCreationTableCreated {
            id: id_generator_table_id,
        });
    }

    struct ItemCreation has key {
        id: UID,
        item_creation_id: SkillTypeItemIdPair,
        version: u64,
        requirements_level: u16,
        base_quantity: u32,
        base_experience: u32,
        base_creation_time: u64,
        energy_cost: u64,
        success_rate: u16,
    }

    public fun id(item_creation: &ItemCreation): object::ID {
        object::uid_to_inner(&item_creation.id)
    }

    public fun item_creation_id(item_creation: &ItemCreation): SkillTypeItemIdPair {
        item_creation.item_creation_id
    }

    public fun version(item_creation: &ItemCreation): u64 {
        item_creation.version
    }

    public fun requirements_level(item_creation: &ItemCreation): u16 {
        item_creation.requirements_level
    }

    public(friend) fun set_requirements_level(item_creation: &mut ItemCreation, requirements_level: u16) {
        item_creation.requirements_level = requirements_level;
    }

    public fun base_quantity(item_creation: &ItemCreation): u32 {
        item_creation.base_quantity
    }

    public(friend) fun set_base_quantity(item_creation: &mut ItemCreation, base_quantity: u32) {
        item_creation.base_quantity = base_quantity;
    }

    public fun base_experience(item_creation: &ItemCreation): u32 {
        item_creation.base_experience
    }

    public(friend) fun set_base_experience(item_creation: &mut ItemCreation, base_experience: u32) {
        item_creation.base_experience = base_experience;
    }

    public fun base_creation_time(item_creation: &ItemCreation): u64 {
        item_creation.base_creation_time
    }

    public(friend) fun set_base_creation_time(item_creation: &mut ItemCreation, base_creation_time: u64) {
        item_creation.base_creation_time = base_creation_time;
    }

    public fun energy_cost(item_creation: &ItemCreation): u64 {
        item_creation.energy_cost
    }

    public(friend) fun set_energy_cost(item_creation: &mut ItemCreation, energy_cost: u64) {
        item_creation.energy_cost = energy_cost;
    }

    public fun success_rate(item_creation: &ItemCreation): u16 {
        item_creation.success_rate
    }

    public(friend) fun set_success_rate(item_creation: &mut ItemCreation, success_rate: u16) {
        item_creation.success_rate = success_rate;
    }

    fun new_item_creation(
        item_creation_id: SkillTypeItemIdPair,
        requirements_level: u16,
        base_quantity: u32,
        base_experience: u32,
        base_creation_time: u64,
        energy_cost: u64,
        success_rate: u16,
        ctx: &mut TxContext,
    ): ItemCreation {
        ItemCreation {
            id: object::new(ctx),
            item_creation_id,
            version: 0,
            requirements_level,
            base_quantity,
            base_experience,
            base_creation_time,
            energy_cost,
            success_rate,
        }
    }

    struct ItemCreationCreated has copy, drop {
        id: option::Option<object::ID>,
        item_creation_id: SkillTypeItemIdPair,
        requirements_level: u16,
        base_quantity: u32,
        base_experience: u32,
        base_creation_time: u64,
        energy_cost: u64,
        success_rate: u16,
    }

    public fun item_creation_created_id(item_creation_created: &ItemCreationCreated): option::Option<object::ID> {
        item_creation_created.id
    }

    public(friend) fun set_item_creation_created_id(item_creation_created: &mut ItemCreationCreated, id: object::ID) {
        item_creation_created.id = option::some(id);
    }

    public fun item_creation_created_item_creation_id(item_creation_created: &ItemCreationCreated): SkillTypeItemIdPair {
        item_creation_created.item_creation_id
    }

    public fun item_creation_created_requirements_level(item_creation_created: &ItemCreationCreated): u16 {
        item_creation_created.requirements_level
    }

    public fun item_creation_created_base_quantity(item_creation_created: &ItemCreationCreated): u32 {
        item_creation_created.base_quantity
    }

    public fun item_creation_created_base_experience(item_creation_created: &ItemCreationCreated): u32 {
        item_creation_created.base_experience
    }

    public fun item_creation_created_base_creation_time(item_creation_created: &ItemCreationCreated): u64 {
        item_creation_created.base_creation_time
    }

    public fun item_creation_created_energy_cost(item_creation_created: &ItemCreationCreated): u64 {
        item_creation_created.energy_cost
    }

    public fun item_creation_created_success_rate(item_creation_created: &ItemCreationCreated): u16 {
        item_creation_created.success_rate
    }

    public(friend) fun new_item_creation_created(
        item_creation_id: SkillTypeItemIdPair,
        requirements_level: u16,
        base_quantity: u32,
        base_experience: u32,
        base_creation_time: u64,
        energy_cost: u64,
        success_rate: u16,
    ): ItemCreationCreated {
        ItemCreationCreated {
            id: option::none(),
            item_creation_id,
            requirements_level,
            base_quantity,
            base_experience,
            base_creation_time,
            energy_cost,
            success_rate,
        }
    }

    struct ItemCreationUpdated has copy, drop {
        id: object::ID,
        item_creation_id: SkillTypeItemIdPair,
        version: u64,
        requirements_level: u16,
        base_quantity: u32,
        base_experience: u32,
        base_creation_time: u64,
        energy_cost: u64,
        success_rate: u16,
    }

    public fun item_creation_updated_id(item_creation_updated: &ItemCreationUpdated): object::ID {
        item_creation_updated.id
    }

    public fun item_creation_updated_item_creation_id(item_creation_updated: &ItemCreationUpdated): SkillTypeItemIdPair {
        item_creation_updated.item_creation_id
    }

    public fun item_creation_updated_requirements_level(item_creation_updated: &ItemCreationUpdated): u16 {
        item_creation_updated.requirements_level
    }

    public fun item_creation_updated_base_quantity(item_creation_updated: &ItemCreationUpdated): u32 {
        item_creation_updated.base_quantity
    }

    public fun item_creation_updated_base_experience(item_creation_updated: &ItemCreationUpdated): u32 {
        item_creation_updated.base_experience
    }

    public fun item_creation_updated_base_creation_time(item_creation_updated: &ItemCreationUpdated): u64 {
        item_creation_updated.base_creation_time
    }

    public fun item_creation_updated_energy_cost(item_creation_updated: &ItemCreationUpdated): u64 {
        item_creation_updated.energy_cost
    }

    public fun item_creation_updated_success_rate(item_creation_updated: &ItemCreationUpdated): u16 {
        item_creation_updated.success_rate
    }

    public(friend) fun new_item_creation_updated(
        item_creation: &ItemCreation,
        requirements_level: u16,
        base_quantity: u32,
        base_experience: u32,
        base_creation_time: u64,
        energy_cost: u64,
        success_rate: u16,
    ): ItemCreationUpdated {
        ItemCreationUpdated {
            id: id(item_creation),
            item_creation_id: item_creation_id(item_creation),
            version: version(item_creation),
            requirements_level,
            base_quantity,
            base_experience,
            base_creation_time,
            energy_cost,
            success_rate,
        }
    }


    public(friend) fun create_item_creation(
        item_creation_id: SkillTypeItemIdPair,
        requirements_level: u16,
        base_quantity: u32,
        base_experience: u32,
        base_creation_time: u64,
        energy_cost: u64,
        success_rate: u16,
        item_creation_table: &mut ItemCreationTable,
        ctx: &mut TxContext,
    ): ItemCreation {
        let item_creation = new_item_creation(
            item_creation_id,
            requirements_level,
            base_quantity,
            base_experience,
            base_creation_time,
            energy_cost,
            success_rate,
            ctx,
        );
        asset_item_creation_id_not_exists_then_add(item_creation_id, item_creation_table, object::uid_to_inner(&item_creation.id));
        item_creation
    }

    public(friend) fun asset_item_creation_id_not_exists(
        item_creation_id: SkillTypeItemIdPair,
        item_creation_table: &ItemCreationTable,
    ) {
        assert!(!table::contains(&item_creation_table.table, item_creation_id), EIdAlreadyExists);
    }

    fun asset_item_creation_id_not_exists_then_add(
        item_creation_id: SkillTypeItemIdPair,
        item_creation_table: &mut ItemCreationTable,
        id: object::ID,
    ) {
        asset_item_creation_id_not_exists(item_creation_id, item_creation_table);
        table::add(&mut item_creation_table.table, item_creation_id, id);
    }

    public(friend) fun transfer_object(item_creation: ItemCreation, recipient: address) {
        assert!(item_creation.version == 0, EInappropriateVersion);
        transfer::transfer(item_creation, recipient);
    }

    public(friend) fun update_version_and_transfer_object(item_creation: ItemCreation, recipient: address) {
        update_object_version(&mut item_creation);
        transfer::transfer(item_creation, recipient);
    }

    #[lint_allow(share_owned)]
    public(friend) fun share_object(item_creation: ItemCreation) {
        assert!(item_creation.version == 0, EInappropriateVersion);
        transfer::share_object(item_creation);
    }

    public(friend) fun freeze_object(item_creation: ItemCreation) {
        assert!(item_creation.version == 0, EInappropriateVersion);
        transfer::freeze_object(item_creation);
    }

    public(friend) fun update_version_and_freeze_object(item_creation: ItemCreation) {
        update_object_version(&mut item_creation);
        transfer::freeze_object(item_creation);
    }

    public(friend) fun update_object_version(item_creation: &mut ItemCreation) {
        item_creation.version = item_creation.version + 1;
        //assert!(item_creation.version != 0, EInappropriateVersion);
    }

    public(friend) fun drop_item_creation(item_creation: ItemCreation) {
        let ItemCreation {
            id,
            item_creation_id: _item_creation_id,
            version: _version,
            requirements_level: _requirements_level,
            base_quantity: _base_quantity,
            base_experience: _base_experience,
            base_creation_time: _base_creation_time,
            energy_cost: _energy_cost,
            success_rate: _success_rate,
        } = item_creation;
        object::delete(id);
    }

    public(friend) fun emit_item_creation_created(item_creation_created: ItemCreationCreated) {
        assert!(std::option::is_some(&item_creation_created.id), EEmptyObjectID);
        event::emit(item_creation_created);
    }

    public(friend) fun emit_item_creation_updated(item_creation_updated: ItemCreationUpdated) {
        event::emit(item_creation_updated);
    }

    #[test_only]
    /// Wrapper of module initializer for testing
    public fun test_init(ctx: &mut TxContext) {
        init(ctx)
    }

}
