// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module infinite_sea::player_aggregate {
    use infinite_sea::player;
    use infinite_sea::player_airdrop_logic;
    use infinite_sea::player_create_logic;
    use infinite_sea::player_deduct_items_logic;
    use infinite_sea::player_increase_experience_and_items_logic;
    use infinite_sea_common::production_material::{Self, ProductionMaterial};
    use sui::tx_context;

    friend infinite_sea::skill_process_start_production_logic;
    friend infinite_sea::skill_process_complete_production_logic;

    const EInvalidPublisher: u64 = 50;

    public entry fun create(
        level: u16,
        experience: u32,
        player_table: &mut player::PlayerTable,
        ctx: &mut tx_context::TxContext,
    ) {
        let player_created = player_create_logic::verify(
            level,
            experience,
            player_table,
            ctx,
        );
        let player = player_create_logic::mutate(
            &player_created,
            player_table,
            ctx,
        );
        player::set_player_created_id(&mut player_created, player::id(&player));
        player::share_object(player);
        player::emit_player_created(player_created);
    }

    public entry fun airdrop(
        player: &mut player::Player,
        publisher: &sui::package::Publisher,
        item_id: u32,
        quantity: u32,
        ctx: &mut tx_context::TxContext,
    ) {
        assert!(sui::package::from_package<player::Player>(publisher), EInvalidPublisher);
        let player_airdropped = player_airdrop_logic::verify(
            item_id,
            quantity,
            player,
            ctx,
        );
        player_airdrop_logic::mutate(
            &player_airdropped,
            player,
            ctx,
        );
        player::update_object_version(player);
        player::emit_player_airdropped(player_airdropped);
    }

    public(friend) fun deduct_items(
        player: &mut player::Player,
        items: vector<ProductionMaterial>,
        ctx: &mut tx_context::TxContext,
    ) {
        let player_items_deducted = player_deduct_items_logic::verify(
            items,
            player,
            ctx,
        );
        player_deduct_items_logic::mutate(
            &player_items_deducted,
            player,
            ctx,
        );
        player::update_object_version(player);
        player::emit_player_items_deducted(player_items_deducted);
    }

    public(friend) fun increase_experience_and_items(
        player: &mut player::Player,
        experience: u32,
        items: vector<ProductionMaterial>,
        new_level: u16,
        ctx: &mut tx_context::TxContext,
    ) {
        let player_experience_and_items_increased = player_increase_experience_and_items_logic::verify(
            experience,
            items,
            new_level,
            player,
            ctx,
        );
        player_increase_experience_and_items_logic::mutate(
            &player_experience_and_items_increased,
            player,
            ctx,
        );
        player::update_object_version(player);
        player::emit_player_experience_and_items_increased(player_experience_and_items_increased);
    }

}
