// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module infinite_sea::player_item {
    friend infinite_sea::player_create_logic;
    friend infinite_sea::player_airdrop_logic;
    friend infinite_sea::player_deduct_items_logic;
    friend infinite_sea::player_increase_experience_and_items_logic;
    friend infinite_sea::player;

    #[allow(unused_const)]
    const EDataTooLong: u64 = 102;

    struct PlayerItem has store {
        item_id: u32,
        quantity: u64,
    }

    public fun item_id(player_item: &PlayerItem): u32 {
        player_item.item_id
    }

    public fun quantity(player_item: &PlayerItem): u64 {
        player_item.quantity
    }

    public(friend) fun set_quantity(player_item: &mut PlayerItem, quantity: u64) {
        player_item.quantity = quantity;
    }

    public(friend) fun new_player_item(
        item_id: u32,
        quantity: u64,
    ): PlayerItem {
        PlayerItem {
            item_id,
            quantity,
        }
    }

    public(friend) fun drop_player_item(player_item: PlayerItem) {
        let PlayerItem {
            item_id: _,
            quantity: _,
        } = player_item;
    }


}
