// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module infinite_sea::skill_process_mutex_aggregate {
    use infinite_sea::skill_process_mutex;
    use sui::tx_context;

    friend infinite_sea::skill_process_service;

}
