// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module infinite_sea_player::player_aggregate {
    use infinite_sea_player::player;
    use sui::tx_context;

}
