// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module infinite_sea_mining::mining_process {
    use std::option;
    use sui::event;
    use sui::object::{Self, UID};
    use sui::table;
    use sui::transfer;
    use sui::tx_context::TxContext;
    friend infinite_sea_mining::mining_process_aggregate;

    const EIdAlreadyExists: u64 = 101;
    #[allow(unused_const)]
    const EDataTooLong: u64 = 102;
    const EInappropriateVersion: u64 = 103;
    const EEmptyObjectID: u64 = 107;

    struct MiningProcessTable has key {
        id: UID,
        table: table::Table<address, object::ID>,
    }

    struct MiningProcessTableCreated has copy, drop {
        id: object::ID,
    }

    fun init(ctx: &mut TxContext) {
        let id_generator_table = MiningProcessTable {
            id: object::new(ctx),
            table: table::new(ctx),
        };
        let id_generator_table_id = object::uid_to_inner(&id_generator_table.id);
        transfer::share_object(id_generator_table);
        event::emit(MiningProcessTableCreated {
            id: id_generator_table_id,
        });
    }

    struct MiningProcess has key {
        id: UID,
        player_id: address,
        version: u64,
        item_id: u32,
        start_time: u64,
        end_time: u64,
    }

    public fun id(mining_process: &MiningProcess): object::ID {
        object::uid_to_inner(&mining_process.id)
    }

    public fun player_id(mining_process: &MiningProcess): address {
        mining_process.player_id
    }

    public fun version(mining_process: &MiningProcess): u64 {
        mining_process.version
    }

    public fun item_id(mining_process: &MiningProcess): u32 {
        mining_process.item_id
    }

    public(friend) fun set_item_id(mining_process: &mut MiningProcess, item_id: u32) {
        mining_process.item_id = item_id;
    }

    public fun start_time(mining_process: &MiningProcess): u64 {
        mining_process.start_time
    }

    public(friend) fun set_start_time(mining_process: &mut MiningProcess, start_time: u64) {
        mining_process.start_time = start_time;
    }

    public fun end_time(mining_process: &MiningProcess): u64 {
        mining_process.end_time
    }

    public(friend) fun set_end_time(mining_process: &mut MiningProcess, end_time: u64) {
        mining_process.end_time = end_time;
    }

    fun new_mining_process(
        player_id: address,
        item_id: u32,
        start_time: u64,
        end_time: u64,
        ctx: &mut TxContext,
    ): MiningProcess {
        MiningProcess {
            id: object::new(ctx),
            player_id,
            version: 0,
            item_id,
            start_time,
            end_time,
        }
    }


    public(friend) fun create_mining_process(
        player_id: address,
        item_id: u32,
        start_time: u64,
        end_time: u64,
        mining_process_table: &mut MiningProcessTable,
        ctx: &mut TxContext,
    ): MiningProcess {
        let mining_process = new_mining_process(
            player_id,
            item_id,
            start_time,
            end_time,
            ctx,
        );
        asset_player_id_not_exists_then_add(player_id, mining_process_table, object::uid_to_inner(&mining_process.id));
        mining_process
    }

    public(friend) fun asset_player_id_not_exists(
        player_id: address,
        mining_process_table: &MiningProcessTable,
    ) {
        assert!(!table::contains(&mining_process_table.table, player_id), EIdAlreadyExists);
    }

    fun asset_player_id_not_exists_then_add(
        player_id: address,
        mining_process_table: &mut MiningProcessTable,
        id: object::ID,
    ) {
        asset_player_id_not_exists(player_id, mining_process_table);
        table::add(&mut mining_process_table.table, player_id, id);
    }

    public(friend) fun transfer_object(mining_process: MiningProcess, recipient: address) {
        assert!(mining_process.version == 0, EInappropriateVersion);
        transfer::transfer(mining_process, recipient);
    }

    public(friend) fun update_version_and_transfer_object(mining_process: MiningProcess, recipient: address) {
        update_object_version(&mut mining_process);
        transfer::transfer(mining_process, recipient);
    }

    #[lint_allow(share_owned)]
    public(friend) fun share_object(mining_process: MiningProcess) {
        assert!(mining_process.version == 0, EInappropriateVersion);
        transfer::share_object(mining_process);
    }

    public(friend) fun freeze_object(mining_process: MiningProcess) {
        assert!(mining_process.version == 0, EInappropriateVersion);
        transfer::freeze_object(mining_process);
    }

    public(friend) fun update_version_and_freeze_object(mining_process: MiningProcess) {
        update_object_version(&mut mining_process);
        transfer::freeze_object(mining_process);
    }

    fun update_object_version(mining_process: &mut MiningProcess) {
        mining_process.version = mining_process.version + 1;
        //assert!(mining_process.version != 0, EInappropriateVersion);
    }

    public(friend) fun drop_mining_process(mining_process: MiningProcess) {
        let MiningProcess {
            id,
            player_id: _player_id,
            version: _version,
            item_id: _item_id,
            start_time: _start_time,
            end_time: _end_time,
        } = mining_process;
        object::delete(id);
    }

    #[test_only]
    /// Wrapper of module initializer for testing
    public fun test_init(ctx: &mut TxContext) {
        init(ctx)
    }

}
