// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module infinite_sea_mining::mining_item_creation_aggregate {
    use infinite_sea_mining::mining_item_creation;
    use sui::tx_context;

}
