spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test10?characterEncoding=utf8&serverTimezone=GMT%2b0&useLegacyDatetimeCode=false
    username: root
    password: qingdao

  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update

server:
  port: 1023

sui:
  contract:
    package-id:
      faucet: "0x2fa64652ba8892074c628353c6411651a2b76bc21cc113fb543be9624edb22d9"
    jsonrpc:
      #url: "https://devnet.baku.movementlabs.xyz"
      #url: "https://fullnode.devnet.sui.io/"
      url: "https://fullnode.testnet.sui.io/"
    package-publish-transactions:
      common: "KPvprtMHVniZTeHXzNkPCxNQL3C9LqzHAVA4GQEjLUz"
      default: "9goES9yDagfzemjrLqzC4Cb9nt1Qbo69KSLkjgQsnNs7"
      nft: "BV4FSb6q9Su5r2EZnesKAy7VVG5bZuAgMEXUWaPfZK4L"
      map: "cWSngBqihSkKTanhmZDuEzJfwj9uUQC467zX6ztc7FF"

    pull-avatar-change-events:
      avatar-change-created:
        fixed-delay: 20000
      avatar-change-deleted:
        fixed-delay: 20000
      avatar-change-updated:
        fixed-delay: 20000
    pull-avatar-events:
      avatar-burned:
        fixed-delay: 20000
      avatar-minted:
        fixed-delay: 5000
      avatar-updated:
        fixed-delay: 10000
      avatar-whitelist-minted:
        fixed-delay: 5000 # 5 seconds
    pull-experience-table-events:
      fixed-delay: 600000 # 10 minutes
    pull-faucet-request:
      fixed-delay: 60000 # 1 minute
    pull-item-creation-events:
      fixed-delay: 600000 # 10 minutes
    pull-item-events:
      fixed-delay: 600000 # 10 minutes
    pull-item-production-events:
      fixed-delay: 600000 # 10 minutes
    pull-map-events:
      fixed-delay: 60000 # 1 minute
    pull-player-events:
      fixed-delay: 10000 # 10 seconds
    pull-roster-events:
      fixed-delay: 10000 # 10 seconds
    pull-ship-battle-events:
      fixed-delay: 10000 # 10 seconds
    pull-ship-events:
      fixed-delay: 10000 # 10 seconds
    pull-skill-process-events:
      fixed-delay: 10000 # 10 seconds
    pull-whitelist-events:
      init-whitelist-event:
        fixed-delay: 60000 # 1 minute
      whitelist-claimed:
        fixed-delay: 20000 # 20 seconds
      whitelist-created:
        fixed-delay: 20000 # 20 seconds
      whitelist-entry-added:
        fixed-delay: 20000 # 20 seconds
      whitelist-entry-updated:
        fixed-delay: 20000 # 20 seconds
      whitelist-updated:
        fixed-delay: 20000 # 20 seconds
    update-all-player-states:
      fixed-delay: 6000 # 6 seconds
    update-all-roster-locations:
      fixed-delay: 6000 # 6 seconds
    update-avatar-change-states:
      fixed-delay: 30000 # 30 seconds
    update-avatar-states:
      fixed-delay: 30000 # 30 seconds
    update-experience-table-states:
      fixed-delay: 10000 # 10 seconds
    update-item-creation-states:
      fixed-delay: 10000 # 10 seconds
    update-item-production-states:
      fixed-delay: 10000 # 10 seconds
    update-item-states:
      fixed-delay: 10000 # 10 seconds
    update-map-states:
      fixed-delay: 30000 # 30 seconds
    update-player-states:
      fixed-delay: 10000 # 10 seconds
    update-roster-states:
      fixed-delay: 10000 # 10 seconds
    update-ship-battle-states:
      fixed-delay: 5000 # 5 seconds
    update-ship-states:
      fixed-delay: 10000 # 10 seconds
    update-skill-process-states:
      fixed-delay: 10000 # 10 seconds
    update-whitelist-states:
      fixed-delay: 10000 # 30 seconds
    update-all-ship-battle-roster-states:
      fixed-delay: 10000 # 3600 seconds