spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test7?characterEncoding=utf8&serverTimezone=GMT%2b0&useLegacyDatetimeCode=false
    # Movement 供内部测试
    username: root
    password: qingdao

  jpa:
    show-sql: false
    properties:
      hibernate:
        hbm2ddl:
          auto: update #TODO change to none

server:
  port: 1023

sui:
  contract:
    package-id:
      faucet: "0x488bac9e56363f9a6cfe68c98aaf519dbaba7d58755d1c489ff6170077e35de9"
    jsonrpc:
      url: "https://devnet.baku.movementlabs.xyz"
      #url: "https://fullnode.devnet.sui.io/"
      #url: "https://fullnode.testnet.sui.io/"
    package-publish-transactions:
      common: "HRybC96PahetWzoYbEqex1uN9o1wzAvK3oyMTMYWk6Ra"
      default: "zDfiwNRegwN1gmFRN13KtimXVTzy1JnNX73CbKaXLfH"
      nft: "FVSvaW4Vor6XhZ4Z6B8FSHk2z7XWMeshin3QzgKeGbmt"
      map: "DqdJ6VeWKSFgshqGapvgfiUpxkG7SnmBjnqdn6uBNdpy"

    pull-avatar-change-events:
      avatar-change-created:
        fixed-delay: 20000
      avatar-change-deleted:
        fixed-delay: 20000
      avatar-change-updated:
        fixed-delay: 20000
    pull-avatar-events:
      avatar-burned:
        fixed-delay: 20000
      avatar-minted:
        fixed-delay: 5000
      avatar-updated:
        fixed-delay: 10000
      avatar-whitelist-minted:
        fixed-delay: 5000 # 5 seconds
    pull-experience-table-events:
      fixed-delay: 600000 # 10 minutes
    pull-faucet-request:
      fixed-delay: 60000 # 1 minute
    pull-item-creation-events:
      fixed-delay: 600000 # 10 minutes
    pull-item-events:
      fixed-delay: 600000 # 10 minutes
    pull-item-production-events:
      fixed-delay: 600000 # 10 minutes
    pull-map-events:
      fixed-delay: 60000 # 1 minute
    pull-player-events:
      fixed-delay: 10000 # 10 seconds
    pull-roster-events:
      fixed-delay: 10000 # 10 seconds
    pull-ship-battle-events:
      fixed-delay: 10000 # 10 seconds
    pull-ship-events:
      fixed-delay: 10000 # 10 seconds
    pull-skill-process-events:
      fixed-delay: 10000 # 10 seconds
    pull-whitelist-events:
      init-whitelist-event:
        fixed-delay: 60000 # 1 minute
      whitelist-claimed:
        fixed-delay: 20000 # 20 seconds
      whitelist-created:
        fixed-delay: 20000 # 20 seconds
      whitelist-entry-added:
        fixed-delay: 20000 # 20 seconds
      whitelist-entry-updated:
        fixed-delay: 20000 # 20 seconds
      whitelist-updated:
        fixed-delay: 20000 # 20 seconds
    update-all-player-states:
      fixed-delay: 6000 # 6 seconds
    update-all-roster-locations:
      fixed-delay: 6000 # 6 seconds
    update-avatar-change-states:
      fixed-delay: 30000 # 30 seconds
    update-avatar-states:
      fixed-delay: 30000 # 30 seconds
    update-experience-table-states:
      fixed-delay: 10000 # 10 seconds
    update-item-creation-states:
      fixed-delay: 10000 # 10 seconds
    update-item-production-states:
      fixed-delay: 10000 # 10 seconds
    update-item-states:
      fixed-delay: 10000 # 10 seconds
    update-map-states:
      fixed-delay: 30000 # 30 seconds
    update-player-states:
      fixed-delay: 10000 # 10 seconds
    update-roster-states:
      fixed-delay: 10000 # 10 seconds
    update-ship-battle-states:
      fixed-delay: 5000 # 5 seconds
    update-ship-states:
      fixed-delay: 10000 # 10 seconds
    update-skill-process-states:
      fixed-delay: 10000 # 10 seconds
    update-whitelist-states:
      fixed-delay: 10000 # 30 seconds
    update-all-ship-battle-roster-states:
      fixed-delay: 10000 # 3600 seconds