spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test9?characterEncoding=utf8&serverTimezone=GMT%2b0&useLegacyDatetimeCode=false
    # Movement 供外人使用
    username: root
    password: qingdao

  jpa:
    show-sql: false
    properties:
      hibernate:
        hbm2ddl:
          auto: update #TODO change to none

server:
  port: 1023

sui:
  contract:
    package-id:
      faucet: "0x2ef33638285dad7062be2670e8aa88d6ec40903dd0ee7ad3e058c93932f1a46a"
    jsonrpc:
      url: "https://devnet.baku.movementlabs.xyz"
      #url: "https://fullnode.devnet.sui.io/"
      #url: "https://fullnode.testnet.sui.io/"
    package-publish-transactions:
      common: "AzeE1Za1BWcTdveKiRmTDYbiqEaCJLeo4Z5ffGUKEYST"
      default: "3e35UDbcHz31sjEL9CK4PNmxNEK4hQFPrpnLPqdM96zU"
      nft: "FrRzJF9jbvjNrXqVKi2LtoZcc1x1ZhAhSGVzTp94PVLF"
      map: "4UrG1cgxiMp5woCigVAULnaWcu5NpBHiYo7UQsQDb3rr"

    pull-avatar-change-events:
      avatar-change-created:
        fixed-delay: 20000
      avatar-change-deleted:
        fixed-delay: 20000
      avatar-change-updated:
        fixed-delay: 20000
    pull-avatar-events:
      avatar-burned:
        fixed-delay: 20000
      avatar-minted:
        fixed-delay: 5000
      avatar-updated:
        fixed-delay: 10000
      avatar-whitelist-minted:
        fixed-delay: 5000 # 5 seconds
    pull-experience-table-events:
      experience-level-added:
        fixed-delay: 6000000 # 100 minutes
      experience-level-updated:
        fixed-delay: 6000000 # 100 minutes
      init-experience-table-event:
        fixed-delay: 6000000 # 100 minutes
    pull-faucet-request:
      fixed-delay: 10000 # 10 seconds
    pull-item-creation-events:
      item-creation-created:
        fixed-delay: 6000000 # 100 minutes
      item-creation-updated:
        fixed-delay: 6000000 # 100 minutes
    pull-item-events:
      item-created:
        fixed-delay: 6000000 # 100 minutes
      item-updated:
        fixed-delay: 6000000 # 100 minutes
    pull-item-production-events:
      item-production-created:
        fixed-delay: 6000000 # 100 minutes
      item-production-updated:
        fixed-delay: 6000000 # 100 minutes
    pull-map-events:
      init-map-event:
        fixed-delay: 36000000 # 10 hours
      island-added:
        fixed-delay: 6000000 # 100 minutes
      island-resources-gathered:
        fixed-delay: 6000000 # 100 minutes
      map-island-claimed:
        fixed-delay: 6000000 # 100 minutes
      map-settings-updated:
        fixed-delay: 6000000 # 100 minutes
      un-whitelisted-for-claiming-island:
        fixed-delay: 6000000 # 100 minutes
      whitelisted-for-claiming-island:
        fixed-delay: 6000000 # 100 minutes
    pull-player-events:
      island-claimed:
        fixed-delay: 6000000 # 100 minutes
      nft-holder-island-claimed:
        fixed-delay: 6000000 # 100 minutes
      player-airdropped:
        fixed-delay: 6000000 # 100 minutes
      player-created:
        fixed-delay: 6000000 # 100 minutes
      player-island-resources-gathered:
        fixed-delay: 6000000 # 100 minutes
    pull-roster-events:
      environment-roster-created:
        fixed-delay: 6000000 # 100 minutes
      roster-created:
        fixed-delay: 6000000 # 100 minutes
      roster-set-sail:
        fixed-delay: 6000000 # 100 minutes
      roster-ship-added:
        fixed-delay: 6000000 # 100 minutes
      roster-ship-inventory-put-in:
        fixed-delay: 6000000 # 100 minutes
      roster-ship-inventory-taken-out:
        fixed-delay: 6000000 # 100 minutes
      roster-ship-inventory-transferred:
        fixed-delay: 6000000 # 100 minutes
      roster-ship-transferred:
        fixed-delay: 6000000 # 100 minutes
      roster-ships-position-adjusted:
        fixed-delay: 6000000 # 100 minutes
    pull-ship-battle-events:
      ship-battle-initiated:
        fixed-delay: 6000000 # 100 minutes
      ship-battle-loot-taken:
        fixed-delay: 6000000 # 100 minutes
      ship-battle-move-made:
        fixed-delay: 6000000 # 100 minutes
    pull-ship-events:
      ship-created:
        fixed-delay: 6000000 # 100 minutes
    pull-skill-process-events:
      creation-process-completed:
        fixed-delay: 6000000 # 100 minutes
      creation-process-started:
        fixed-delay: 6000000 # 100 minutes
      production-process-completed:
        fixed-delay: 6000000 # 100 minutes
      production-process-started:
        fixed-delay: 6000000 # 100 minutes
      ship-production-process-completed:
        fixed-delay: 6000000 # 100 minutes
      ship-production-process-started:
        fixed-delay: 6000000 # 100 minutes
      skill-process-created:
        fixed-delay: 6000000 # 100 minutes
    pull-whitelist-events:
      init-whitelist-event:
        fixed-delay: 6000000 # 100 minutes
      whitelist-claimed:
        fixed-delay: 6000000 # 100 minutes
      whitelist-created:
        fixed-delay: 6000000 # 100 minutes
      whitelist-entry-added:
        fixed-delay: 6000000 # 100 minutes
      whitelist-entry-updated:
        fixed-delay: 6000000 # 100 minutes
      whitelist-updated:
        fixed-delay: 6000000 # 100 minutes
    update-all-player-states:
      fixed-delay: 6000000 # 100 minutes
    update-all-roster-locations:
      fixed-delay: 6000000 # 100 minutes
    update-avatar-change-states:
      fixed-delay: 5000
    update-avatar-states:
      fixed-delay: 5000
    update-experience-table-states:
      fixed-delay: 6000000 # 100 minutes
    update-item-creation-states:
      fixed-delay: 6000000 # 100 minutes
    update-item-production-states:
      fixed-delay: 6000000 # 100 minutes
    update-item-states:
      fixed-delay: 6000000 # 100 minutes
    update-map-states:
      fixed-delay: 6000000 # 100 minutes
    update-player-states:
      fixed-delay: 6000000 # 100 minutes
    update-roster-states:
      fixed-delay: 6000000 # 100 minutes
    update-ship-battle-states:
      fixed-delay: 6000000 # 100 minutes
    update-ship-states:
      fixed-delay: 6000000 # 100 minutes
    update-skill-process-states:
      fixed-delay: 6000000 # 100 minutes
    update-whitelist-states:
      fixed-delay: 10000 # 10 seconds
    update-all-roster-states:
      fixed-delay: 10000 # 10 seconds

    # =================== Only for Avatar NFT Launch, END ===================

